import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">Homepage</Link>
        </li>
        <li>
          <Link to="/faisaldirectorymodulesearchpagevtubechannel">
            FaisalDirectoryModuleSearchPageVTubeChannel
          </Link>
        </li>
        <li>
          <Link to="/faisaldirectorymodulevguidemainpage">
            FaisalDirectoryModuleVGuideMainPage
          </Link>
        </li>
        <li>
          <Link to="/faisaldirectorymodulesearchpagevguidepersonalprofile">
            FaisalDirectoryModuleSearchPageVGuidePersonalProfile
          </Link>
        </li>
        <li>
          <Link to="/faisaldirectorymodulesearchpagevguidebusinessprofile">
            FaisalDirectoryModuleSearchPageVGuideBusinessProfile
          </Link>
        </li>
        <li>
          <Link to="/faisaldirectorymodulesearchpagevblogpost">
            FaisalDirectoryModuleSearchPageVBlogPost
          </Link>
        </li>
        <li>
          <Link to="/faisaldirectorymodulesearchpagevnationsocialpage">
            FaisalDirectoryModuleSearchPageVNationSocialPage
          </Link>
        </li>
        <li>
          <Link to="/faisaldirectorymodulesearchpagevnationsocialgroup">
            FaisalDirectoryModuleSearchPageVNationSocialGroup
          </Link>
        </li>
        <li>
          <Link to="/faisaldirectorymodulesearchpagevtubevideo">
            FaisalDirectoryModuleSearchPageVTubeVideo
          </Link>
        </li>
        <li>
          <Link to="/faisaldirectorymodulesearchpagevjobsvacancy">
            FaisalDirectoryModuleSearchPageVJobsVacancy
          </Link>
        </li>
        <li>
          <Link to="/faisaldirectorymodulesearchpagevcollegecourse">
            FaisalDirectoryModuleSearchPageVCollegeCourse
          </Link>
        </li>
        <li>
          <Link to="/faisaldirectorymodulesearchpagevmarketstore">
            FaisalDirectoryModuleSearchPageVMarketStore
          </Link>
        </li>
        <li>
          <Link to="/faisaldirectorymodulesearchpagevmarketproduct">
            FaisalDirectoryModuleSearchPageVMarketProduct
          </Link>
        </li>
        <li>
          <Link to="/faisaldirectorymodulesearchpagevlanceservice">
            FaisalDirectoryModuleSearchPageVLanceService
          </Link>
        </li>
        <li>
          <Link to="/faisaldirectorymodulesearchpagevlanceproject">
            FaisalDirectoryModuleSearchPageVLanceProject
          </Link>
        </li>
        <li>
          <Link to="/faisaldirectorymodulesearchpageveventsevent">
            FaisalDirectoryModuleSearchPageVEventsEvent
          </Link>
        </li>
        <li>
          <Link to="/faisaldirectorymodulesearchpageveventsvenue">
            FaisalDirectoryModuleSearchPageVEventsVenue
          </Link>
        </li>
        <li>
          <Link to="/faisaldirectorymodulesearchpagevwebinarswebinar">
            FaisalDirectoryModuleSearchPageVWebinarsWebinar
          </Link>
        </li>
        <li>
          <Link to="/faisaldirectorymodulesearchpagevexpertconsultation">
            FaisalDirectoryModuleSearchPageVExpertConsultation
          </Link>
        </li>
        <li>
          <Link to="/thestoryandtheproudvideossection">
            ThestoryandTheProudVideossection
          </Link>
        </li>
        <li>
          <Link to="/letsshowyoutheawsomeness">LetsShowYoutheawsomeness</Link>
        </li>
        <li>
          <Link to="/youthinkwearedone">YouThinkWeAreDone</Link>
        </li>
        <li>
          <Link to="/items">Items</Link>
        </li>
        <li>
          <Link to="/imarnfrontendwebsiteaioprofileprofilesectionendorsebuttonclickedanywhereinthesite">
            IMARNFrontendWebsiteAIOProfileProfileSectionEndorseButtonClickedanywhereinthesite
          </Link>
        </li>
        <li>
          <Link to="/imarnfrontendwebsiteaioprofileprofilesectionendorsesendbuttonclicked">
            IMARNFrontendWebsiteAIOProfileProfileSectionEndorseSendButtonClicked
          </Link>
        </li>
        <li>
          <Link to="/imarnfrontendwebsiteaioprofilesocialsectionlikesnoclicked">
            IMARNFrontendWebsiteAIOProfileSocialSectionLikesNoClicked
          </Link>
        </li>
        <li>
          <Link to="/imarnfrontendwebsiteaioprofilesocialsectionsharebuttonclicked">
            IMARNFrontendWebsiteAIOProfileSocialSectionShareButtonClicked
          </Link>
        </li>
        <li>
          <Link to="/deletemodal">Deletemodal</Link>
        </li>
        <li>
          <Link to="/imarnfrontendwebsiteaioprofilegeneralsection">
            IMARNFrontendWebsiteAIOProfileGeneralSection
          </Link>
        </li>
        <li>
          <Link to="/imarnfrontendwebsiteaioprofileprofilesectioncoverletter">
            IMARNFrontendWebsiteAIOProfileProfileSectionCoverLetter
          </Link>
        </li>
        <li>
          <Link to="/imarnfrontendwebsiteaioprofileprofilesectionworkexperience">
            IMARNFrontendWebsiteAIOProfileProfileSectionWorkExperience
          </Link>
        </li>
        <li>
          <Link to="/imarnfrontendwebsiteaioprofileprofilesectioneducation">
            IMARNFrontendWebsiteAIOProfileProfileSectionEducation
          </Link>
        </li>
        <li>
          <Link to="/imarnfrontendwebsiteaioprofileprofilesectionskills">
            IMARNFrontendWebsiteAIOProfileProfileSectionSkills
          </Link>
        </li>
        <li>
          <Link to="/imarnfrontendwebsiteaioprofileprofilesectionacheivements">
            IMARNFrontendWebsiteAIOProfileProfileSectionAcheivements
          </Link>
        </li>
        <li>
          <Link to="/imarnfrontendwebsiteaioprofileprofilesectionendorsementsreceived">
            IMARNFrontendWebsiteAIOProfileProfileSectionEndorsementsReceived
          </Link>
        </li>
        <li>
          <Link to="/imarnfrontendwebsiteaioprofileprofilesectionendorsementsgiven">
            IMARNFrontendWebsiteAIOProfileProfileSectionEndorsementsGiven
          </Link>
        </li>
        <li>
          <Link to="/imarnfrontendwebsiteaioprofilesocialsectiontimeline">
            IMARNFrontendWebsiteAIOProfileSocialSectionTimeline
          </Link>
        </li>
        <li>
          <Link to="/imarnfrontendwebsiteaioprofilesocialsectiongalleryphotos">
            IMARNFrontendWebsiteAIOProfileSocialSectionGalleryPhotos
          </Link>
        </li>
        <li>
          <Link to="/imranfrontendwebsiteaioprofilesocialsectiongalleryalbummodal">
            ImranFrontendWebsiteAIOProfileSocialSectionGalleryAlbumModal
          </Link>
        </li>
        <li>
          <Link to="/imarnfrontendwebsiteaioprofilesocialsectiongalleryvideos">
            IMARNFrontendWebsiteAIOProfileSocialSectionGalleryVideos
          </Link>
        </li>
        <li>
          <Link to="/imarnfrontendwebsiteaioprofilesocialsectiongalleryalbums">
            IMARNFrontendWebsiteAIOProfileSocialSectionGalleryAlbums
          </Link>
        </li>
        <li>
          <Link to="/imarnfrontendwebsiteaioprofilesocialsectionconnections">
            IMARNFrontendWebsiteAIOProfileSocialSectionConnections
          </Link>
        </li>
        <li>
          <Link to="/imarnfrontendwebsiteaioprofilesocialsectionfollowers">
            IMARNFrontendWebsiteAIOProfileSocialSectionFollowers
          </Link>
        </li>
        <li>
          <Link to="/imarnfrontendwebsiteaioprofilesocialsectionfollowing">
            IMARNFrontendWebsiteAIOProfileSocialSectionFollowing
          </Link>
        </li>
        <li>
          <Link to="/imarnfrontendwebsiteaioprofilesocialsectionlikedpages">
            IMARNFrontendWebsiteAIOProfileSocialSectionLikedPages
          </Link>
        </li>
        <li>
          <Link to="/imarnfrontendwebsiteaioprofilesocialsectionjoinedgroups">
            IMARNFrontendWebsiteAIOProfileSocialSectionJoinedGroups
          </Link>
        </li>
        <li>
          <Link to="/imarnfrontendwebsiteaioprofilesocialsectionsubscribedchannels">
            IMARNFrontendWebsiteAIOProfileSocialSectionSubscribedChannels
          </Link>
        </li>
        <li>
          <Link to="/imarnfrontendwebsiteaioprofileperformance">
            IMARNFrontendWebsiteAIOProfilePerformance
          </Link>
        </li>
        <li>
          <Link to="/imarnfrontendwebsiteaioprofileassetsvauthor">
            IMARNFrontendWebsiteAIOProfileAssetsVAuthor
          </Link>
        </li>
        <li>
          <Link to="/imarnfrontendwebsiteaioprofileassetsvemployer">
            IMARNFrontendWebsiteAIOProfileAssetsVEmployer
          </Link>
        </li>
        <li>
          <Link to="/imarnfrontendwebsiteaioprofileassetsvinstructor">
            IMARNFrontendWebsiteAIOProfileAssetsVInstructor
          </Link>
        </li>
        <li>
          <Link to="/imarnfrontendwebsiteaioprofileassetsvvendor">
            IMARNFrontendWebsiteAIOProfileAssetsVVendor
          </Link>
        </li>
        <li>
          <Link to="/imarnfrontendwebsiteaioprofileassetsvlancer">
            IMARNFrontendWebsiteAIOProfileAssetsVLancer
          </Link>
        </li>
        <li>
          <Link to="/imarnfrontendwebsiteaioprofileassetsvorganizer">
            IMARNFrontendWebsiteAIOProfileAssetsVOrganizer
          </Link>
        </li>
        <li>
          <Link to="/imarnfrontendwebsiteaioprofileassetsvhost">
            IMARNFrontendWebsiteAIOProfileAssetsVHost
          </Link>
        </li>
        <li>
          <Link to="/imarnfrontendwebsiteaioprofileassetsvspeaker">
            IMARNFrontendWebsiteAIOProfileAssetsVSpeaker
          </Link>
        </li>
        <li>
          <Link to="/imarnfrontendwebsiteaioprofileassetsvexpert">
            IMARNFrontendWebsiteAIOProfileAssetsVExpert
          </Link>
        </li>
        <li>
          <Link to="/imarnfrontendwebsiteaioprofilesponsorshipsponsoredby">
            IMARNFrontendWebsiteAIOProfileSponsorshipSponsoredBy
          </Link>
        </li>
        <li>
          <Link to="/imarnfrontendwebsiteaioprofilesponsorshipsponsoring">
            IMARNFrontendWebsiteAIOProfileSponsorshipSponsoring
          </Link>
        </li>
        <li>
          <Link to="/imranfrontendwebsiteaioprofilesocialsectiongalleryphotomodal">
            ImranFrontendWebsiteAIOProfileSocialSectionGalleryPhotoModal
          </Link>
        </li>
        <li>
          <Link to="/imranfrontendwebsiteaioprofilesocialsectiongalleryvideomodal">
            ImranFrontendWebsiteAIOProfileSocialSectionGalleryVideoModal
          </Link>
        </li>
        <li>
          <Link to="/imarnfrontendwebsitesingleservicepagecheckoutscenerio2fundwalletmodalbox">
            IMARNFrontendWebsiteSingleServicePageCheckoutScenerio2FundWalletModalbox
          </Link>
        </li>
        <li>
          <Link to="/imarnfrontendwebsitesingleservicepagecheckoutscenerio2fundwalletmodalboxaddanothercard">
            IMARNFrontendWebsiteSingleServicePageCheckoutScenerio2FundWalletModalboxAddAnotherCard
          </Link>
        </li>
        <li>
          <Link to="/vlancemainpage">VLanceMainPage</Link>
        </li>
        <li>
          <Link to="/faisalfreelancingmodulesingleservicepage">
            FaisalFreelancingModuleSingleServicePage
          </Link>
        </li>
        <li>
          <Link to="/faisalfreelancingmodulesingleservicepagecheckoutscenrio1hasenoughbalancetofundtheproject">
            FaisalFreelancingModuleSingleServicePageCheckoutScenrio1Hasenoughbalancetofundtheproject
          </Link>
        </li>
        <li>
          <Link to="/faisalfreelancingmodulesingleservicepagecheckoutscenrio2haslowerbalanceandneedtoaddbalancetothewalletinordertofundtheprojectone">
            FaisalFreelancingModuleSingleServicePageCheckoutScenrio2HaslowerbalanceandneedtoaddbalancetothewalletinordertofundtheprojectOne
          </Link>
        </li>
        <li>
          <Link to="/faisalfreelancingmodulesingleservicepageovervieworderplaced">
            FaisalFreelancingModuleSingleServicePageOverviewOrderPlaced
          </Link>
        </li>
        <li>
          <Link to="/faisalfreelancingmodulesingleprojectpagedetailsone">
            FaisalFreelancingModuleSingleProjectPageDetailsOne
          </Link>
        </li>
        <li>
          <Link to="/faisalfreelancingmodulesingleprojectpagerequirementsone">
            FaisalFreelancingModuleSingleProjectPageRequirementsOne
          </Link>
        </li>
        <li>
          <Link to="/faisalfreelancingmodulesingleprojectpagedelivery">
            FaisalFreelancingModuleSingleProjectPageDelivery
          </Link>
        </li>
        <li>
          <Link to="/faisalfreelancingmodulesingleprojectpagemessages">
            FaisalFreelancingModuleSingleProjectPageMessages
          </Link>
        </li>
        <li>
          <Link to="/faisalfreelancingmodulesingleservicepagecheckoutscenrio2haslowerbalanceandneedtoaddbalancetothewalletinordertofundtheproject">
            FaisalFreelancingModuleSingleServicePageCheckoutScenrio2Haslowerbalanceandneedtoaddbalancetothewalletinordertofundtheproject
          </Link>
        </li>
        <li>
          <Link to="/faisalfreelancingmodulesingleservicepageoverviewordercancelled">
            FaisalFreelancingModuleSingleServicePageOverviewOrderCancelled
          </Link>
        </li>
        <li>
          <Link to="/faisalfreelancingmodulesingleservicepageovervieworderdelivered">
            FaisalFreelancingModuleSingleServicePageOverviewOrderDelivered
          </Link>
        </li>
        <li>
          <Link to="/imarnfrontendwebsitesingleprojectpagecheckoutscenerio2fundwalletmodalbox">
            IMARNFrontendWebsiteSingleProjectPageCheckoutScenerio2FundWalletModalbox
          </Link>
        </li>
        <li>
          <Link to="/imarnfrontendwebsitesingleprojectpagecheckoutscenerio2fundwalletmodalboxaddanothercard">
            IMARNFrontendWebsiteSingleProjectPageCheckoutScenerio2FundWalletModalboxAddAnotherCard
          </Link>
        </li>
        <li>
          <Link to="/reportmodalbox">ReportModalbox</Link>
        </li>
        <li>
          <Link to="/faisalfreelancingmodulepostedprojectpagewhennotapplied">
            FaisalfreelancingModulePostedProjectPageWhennotApplied
          </Link>
        </li>
        <li>
          <Link to="/faisalfreelancingmodulesingleprojectpagecheckoutscenriohasenoughbalancetofundtheproject">
            FaisalFreelancingModuleSingleProjectPageCheckoutScenrioHasenoughbalancetofundtheproject
          </Link>
        </li>
        <li>
          <Link to="/faisalfreelancingmodulesingleprojectpagecheckoutscenrio2haslowerbalanceandneedtoaddbalancetothewalletinordertofundtheproject">
            FaisalFreelancingModuleSingleProjectPageCheckoutScenrio2Haslowerbalanceandneedtoaddbalancetothewalletinordertofundtheproject
          </Link>
        </li>
        <li>
          <Link to="/faisalfreelancingmodulesingleprojectpageoverviewprojectplaced">
            FaisalFreelancingModuleSingleProjectPageOverviewProjectPlaced
          </Link>
        </li>
        <li>
          <Link to="/faisalfreelancingmodulesingleprojectpagedetails">
            FaisalFreelancingModuleSingleProjectPageDetails
          </Link>
        </li>
        <li>
          <Link to="/faisalfreelancingmodulesingleprojectpagerequirements">
            FaisalFreelancingModuleSingleProjectPageRequirements
          </Link>
        </li>
        <li>
          <Link to="/faisalfreelancingmodulesingleprojectpagedeliveryone">
            FaisalFreelancingModuleSingleProjectPageDeliveryOne
          </Link>
        </li>
        <li>
          <Link to="/faisalfreelancingmodulesingleprojectpagemessagesone">
            FaisalFreelancingModuleSingleProjectPageMessagesOne
          </Link>
        </li>
        <li>
          <Link to="/faisalfreelancingmodulesingleprojectpagecheckoutscenrio2haslowerbalanceandneedtoaddbalancetothewalletinordertofundtheprojectone">
            FaisalFreelancingModuleSingleProjectPageCheckoutScenrio2HaslowerbalanceandneedtoaddbalancetothewalletinordertofundtheprojectOne
          </Link>
        </li>
        <li>
          <Link to="/faisalfreelancingmodulesingleprojectpageoverviewordercancelled">
            FaisalFreelancingModuleSingleProjectPageOverviewOrderCancelled
          </Link>
        </li>
        <li>
          <Link to="/faisalfreelancingmodulepostedprojectpagewhenapplied">
            FaisalfreelancingModulePostedProjectPageWhenApplied
          </Link>
        </li>
        <li>
          <Link to="/faisalfreelancingmodulesingleprojectpageovervieworderdelivered">
            FaisalFreelancingModuleSingleProjectPageOverviewOrderDelivered
          </Link>
        </li>
        <li>
          <Link to="/faisalfreelancingmodulepostedprojectpageupdateproposal">
            FaisalfreelancingModulePostedProjectPageUpdateProposal
          </Link>
        </li>
        <li>
          <Link to="/imranvideonetworkmodulevtubemainpage">
            ImranVideoNetworkModuleVTubeMainPage
          </Link>
        </li>
        <li>
          <Link to="/imranvideonetworkmodulevtubesinglepage">
            ImranVideoNetworkModuleVTubeSinglePage
          </Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;
